### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by OleRoel** [demyxco/code-server#4]
My first step with code-server was writing a simple "Hello, world!" in Python. Everything looks great, but the next step to execute my little code failed with 

```shell
zsh: command not found: python
```

My attempt to install Python wasn't very successful:

```shell
apt-get update
Reading package lists... Done
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
```

Am I missing something the workflow, like write code in code-server container and execute it in another Python container approach?

Any help would be appreciated. Thanks!

**Comment by demyxco** [comment]
Hi, there are two ways to install python:

1. `sudo apt update && sudo apt install python`
2. Clone this repo, open Dockerfile, and add python to the packages RUN command

First one is temporary and the second one is permanent. Whatever you choose is up to you; think of my repo as a template for you to modify to fit your needs.

I hope this helps!

**Comment by OleRoel** [comment]
Thank you for your quick reply. I just slapped my forehead very hard. `sudo` works. To my excuse: it was quite hot today in northern Germany and my brain seems to shut down at that temperature... (and I tried `sudo` in combination with another command that didn't work).

**Comment by demyxco** [comment]
It's ok, we all get those days where our brain is just fried! It's actually pretty hot here in California, it's gonna hit over 100F (highest 40C).

Thanks for using my code-server image!
